name: Create Testing Backup Container

on:
  push:
    branches: [testing]

jobs:
  build-app:
    name: Build Testing Container
    runs-on: ubuntu-latest
    env:
      TAG: loadorderlibrary-backup
      USER: ${{ github.repository_owner }}
      REGISTRY: ghcr.io
      VERSION: testing
    steps:
      - uses: actions/checkout@main

      - name: Build Container Image
        run: docker build --target backup-testing -t $TAG -f docker/testing/app/Dockerfile .

      - name: Push to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
          docker tag $TAG ${{ env.REGISTRY }}/$USER/$TAG:${{ env.VERSION }}
          docker push ${{ env.REGISTRY }}/$USER/$TAG:${{ env.VERSION }}

  deploy:
    name: Deploy Container to Server
    runs-on: ubuntu-latest
    needs: [build-app]
    steps:
      - name: SSH and deploy
        run: |
          echo "${{ secrets.TESTING_KEY }}" > id_meow
          chmod 600 id_meow
          ssh -p ${{ secrets.TESTING_PORT }} -i id_meow "${{ secrets.TESTING_USER }}"@"${{ secrets.TESTING_HOST }}" -o "StrictHostKeyChecking no" "sudo ${{ secrets.TESTING_DEPLOY }}"
