name: Create Production Backup Container

on:
  push:
    branches: [main]

jobs:
  build-app:
    name: Build Production Container
    runs-on: ubuntu-latest
    env:
      TAG: loadorderlibrary-backup
      REGISTRY: ghcr.io
      VERSION: latest
    steps:
      - uses: actions/checkout@main

      - name: Build Container Image
        run: docker build --target backup-prod -t $TAG -f docker/prod/app/Dockerfile .

      - name: Push to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
          docker tag $TAG ${{ env.REGISTRY }}/${{ secrets.OWNER_LC }}/$TAG:${{ env.VERSION }}
          docker push ${{ env.REGISTRY }}/${{ secrets.OWNER_LC }}/$TAG:${{ env.VERSION }}

  deploy:
    name: Deploy Container to Server
    runs-on: ubuntu-latest
    needs: [build-app]
    steps:
      - name: SSH and deploy
        run: |
          echo "${{ secrets.PROD_KEY }}" > id_meow
          chmod 600 id_meow
          ssh -p ${{ secrets.PROD_PORT }} -i id_meow "${{ secrets.PROD_USER }}"@"${{ secrets.PROD_HOST }}" -o "StrictHostKeyChecking no" "sudo ${{ secrets.PROD_DEPLOY }}"
